const Types = {
  PATIENT_REGISTER_REQUEST: '@patient/PATIENT_REGISTER_REQUEST',
  PATIENT_REGISTER_SUCCESS: '@patient/PATIENT_REGISTER_SUCCESS',
  PATIENT_REGISTER_FAILURE: '@patient/PATIENT_REGISTER_FAILURE',
};

export default Types;
